"""Add game_user Association Table

Revision ID: 1df3e2baf30d
Revises: 417dad11589a
Create Date: 2023-10-01 23:06:22.650318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df3e2baf30d'
down_revision = '417dad11589a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
